version: '3'

services:
  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - database
    restart: always
    volumes:
      - redis:/bitnami/redis
  wild-overflow:
    image: vcwild/wildoverflow:0.4.5
    container_name: wildoverflow
    networks:
      - database
    env_file: .env
    restart: always

volumes:
  redis:
    driver: local

networks:
  database:
    driver: bridge
