version: '2'

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - database
  wild-overflow:
    image: 'vcwild/wildoverflow:latest'
    networks:
      - database
    #   - REDIS_PASSWORD=redispass
    # networks:
    #   - app-tier
    # myapp:
    #   image: 'YOUR_APPLICATION_IMAGE'
    #   networks:
    #     - app-tier

networks:
  database:
    driver: bridge
