version: '3'

services:
  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - database
    restart: always
  wild-overflow:
    image: vcwild/wildoverflow:0.4.3
    networks:
      - database
    env_file: .env
    restart: always

networks:
  database:
    driver: bridge
