version: '2'

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      #   - REDIS_PASSWORD=redispass
    networks:
      - database
    restart: always
  wild-overflow:
    image: 'vcwild/wildoverflow:latest'
    networks:
      - database
    restart: always

networks:
  database:
    driver: bridge
